//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauThauOnline.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BenMoiThauDaDuyet
    {
        public int ID { get; set; }
        [DisplayName("Mã cơ quan")]
        public string Mã_cơ_quan { get; set; }
        [Required(ErrorMessage = "Bắt buộc.")]
        [DisplayName("Bên mời thầu")]
        public string Bên_mời_thầu { get; set; }
        [DisplayName("Địa chỉ")]
        public string Địa_chỉ { get; set; }
        [DisplayName("Số điện thoại")]
        public string Số_điện_thoại { get; set; }
        [DisplayName("Tên viết tắt")]
        public string Tên_viết_tắt { get; set; }
        [DisplayName("Tên tiếng Anh")]
        public string Tên_tiếng_Anh { get; set; }
        [DisplayName("Phân loại trực thuộc")]
        public string Phân_loại_trực_thuộc { get; set; }
        public string Tập_đoàn_TCT_Bộ_ban_ngành { get; set; }
        [DisplayName("Tỉnh/ Thành phố")]
        public string Tỉnh_Thành_Phố { get; set; }
        [DisplayName("Số Fax cơ quan")]
        public string Số_Fax_cơ_quan { get; set; }
        [DisplayName("Trang web")]
        public string Trang_web { get; set; }
        [DisplayName("Hình thái kinh doanh")]
        public string Hình_thái_kinh_doanh { get; set; }
        [DisplayName("Mã số thuế")]
        public string Mã_số_thuế { get; set; }
        [DisplayName("Ngành nghề")]
        public string Ngành_nghề { get; set; }
        public Nullable<System.DateTime> Ngày_phê_duyệt { get; set; }
        public string Số_ĐKKD { get; set; }
        public Nullable<int> AccountID { get; set; }

        public Tỉnh_Thành_phố? Tỉnh_Thành_phố_EnumValue { get; set; }
        public Phân_loại_trực_thuộc Phân_loại_trực_thuộc_EnumValue { get; set; }
        public Tập_đoàn_TCT? Tập_đoàn_TCT_EnumValue { get; set; }
        public Bộ_ban_ngành? Bộ_ban_ngành_EnumValue { get; set; }

    }
}
