//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauThauOnline.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class ThongBaoMoiThau_ThongTinChiTiet
    {
        [HiddenInput(DisplayValue = false)]
        [Key]
        public int ID { get; set; }
        [DisplayName("Số TBMT")]
        public string Số_TBMT { get; set; }
        [DisplayName("Số hiệu KHLCNT")]
        public string Số_hiệu_KHLCNT { get; set; }
        [DisplayName("Tên KHLCNT")]
        public string Tên_KHLCNT { get; set; }
        [DisplayName("Lĩnh vực")]
        public string Lĩnh_vực { get; set; }
        [DisplayName("Bên mời thầu")]
        public string Bên_mời_thầu { get; set; }
        [Required(ErrorMessage = "Bắt buộc.")]
        [DisplayName("Tên gói thầu")]
        public string Tên_gói_thầu { get; set; }
        [DisplayName("Phân loại")]
        public string Phân_loại { get; set; }
        [DisplayName("Tên dự toán mua sắm")]
        public string Tên_dự_toán_mua_sắm { get; set; }
        [DisplayName("Chi tiết nguồn vốn")]
        public string Chi_tiết_nguồn_vốn { get; set; }
        [DisplayName("Loại hợp đồng")]
        public string Loại_hợp_đồng { get; set; }
        [DisplayName("Hình thức lựa chọn nhà thầu")]
        public string Hình_thức_lựa_chọn_nhà_thầu { get; set; }
        [DisplayName("Phương thức LCNT")]
        public string Phương_thức_LCNT { get; set; }
        [DisplayName("Thời gian thực hiện hợp đồng (ngày)")]
        public Nullable<int> Thời_gian_thực_hiện_hợp_đồng { get; set; }
        [DisplayName("Hình thức dự thầu")]
        public string Hình_thức_dự_thầu { get; set; }
        [DisplayName("Thời gian nhận E-HSDT từ ngày")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Thời_gian_nhận_E_HSDT_từ_ngày { get; set; }
        [DisplayName("Thời gian nhận E-HSDT đến ngày")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Thời_gian_nhận_E_HSDT_đến_ngày { get; set; }
        [DisplayName("Chi phí E-HSMT")]
        public Nullable<long> Chi_phí_E_HSMT { get; set; }
        [DisplayName("Thời gian hiệu lực của E-HSDT (ngày)")]
        public Nullable<int> Thời_gian_hiệu_lực_của_E_HSDT { get; set; }
        [DisplayName("Địa điểm nhận HSDT")]
        public string Địa_điểm_nhận_HSDT { get; set; }
        [DisplayName("Địa điểm thực hiện gói thầu")]
        public string Địa_điểm_thực_hiện_gói_thầu { get; set; }
        [DisplayName("Thời điểm đóng mở thầu")]
        [DataType(DataType.DateTime)]
        public Nullable<DateTime> Thời_điểm_đóng_mở_thầu { get; set; }
        [DisplayName("Địa điểm mở thầu")]
        public string Địa_điểm_mở_thầu { get; set; }
        [DisplayName("Dự toán gói thầu (VND)")]
        public Nullable<long> Dự_toán_gói_thầu { get; set; }
        [DisplayName("Số tiền bảo đảm dự thầu (VND)")]
        public Nullable<long> Số_tiền_bảo_đảm_dự_thầu { get; set; }
        [DisplayName("Hình thức bảo đảm dự thầu")]
        public string Hình_thức_bảo_đảm_dự_thầu { get; set; }
        [DisplayName("Hồ sơ mời thầu")]
        public string Hồ_sơ_mời_thầu { get; set; }
        [DisplayName("Làm rõ E-HSMT")]
        public string Làm_rõ_E_HSMT { get; set; }
        [DisplayName("Thời điểm đăng tải")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Thời_điểm_đăng_tải { get; set; }
        public Nullable<int> Lần_chỉnh_sửa { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> BenMoiThauID { get; set; }


        public Lĩnh_vực Lĩnh_vực_EnumValue { get; set; }
        public Phân_loại Phân_loại_EnumValue { get; set; }
        public Loại_hợp_đồng Loại_hợp_đồng_EnumValue { get; set; }
        public Hình_thức_lựa_chọn_nhà_thầu Hình_thức_lựa_chọn_nhà_thầu_EnumValue { get; set; }
        public Phương_thức_LCNT Phương_thức_LCNT_EnumValue { get; set; }
        public Hình_thức_dự_thầu Hình_thức_dự_thầu_EnumValue { get; set; }
        public Hình_thức_bảo_đảm_dự_thầu Hình_thức_bảo_đảm_dự_thầu_EnumValue { get; set; }
    }


}